- name: Deploy 3x-ui
  hosts: all
  become: false
  vars:
    deploy_compose_service_name: 3x-ui

  tasks:
    - name: Docker compose up {{ deploy_compose_service_name }}
      ansible.builtin.import_role:
        name: deploy_compose
      vars:
        deploy_compose_file: compose.yaml
      environment:
        X_UI_VERSION: "v2.8.5"
