- name: Run monitoring services in docker compose
  ansible.builtin.import_role:
    name: deploy_compose
  vars:
    deploy_compose_dir: "/srv/monitoring"
    deploy_compose_file: compose.yaml
    deploy_compose_service_name: monitoring_client
  environment:
    CADVISOR_VERSION: "{{ monitoring_client_cadvizor_version }}"
    NODEEXPORTER_VERSION: "{{ monitoring_client_node_exporter_version }}"
