- name: Generate node config
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - "{{ lookup('env', 'PWD') }}/node/node_config_vars.yaml"

  tasks:
    - name: Generate root node host file
      ansible.builtin.template:
        src: "root_node_host.yaml.j2"
        dest: "root_node_host.yaml"
        mode: "0644"
