services:
  hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:1.1.14
    restart: unless-stopped
    networks:
      - rustdesk_network
    ports:
      # - "21114:21114"
      - "915:21115"
      - "916:21116"
      - "916:21116/udp"
      - "918:21118"
    volumes:
      - ./data:/root
    command: hbbs

  hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:1.1.14
    restart: unless-stopped
    networks:
      - rustdesk_network
    ports:
      - "917:21117"
      - "919:21119"
    volumes:
      - ./data:/root
    command: hbbr

networks:
  rustdesk_network:
    driver: bridge
